name: operator-tests

on: 
  pull_request:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  tests:
    name: Unit tests and coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
    - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
          go-version: "^1.17.4"
    - name: Make dependencies
      run: make deps mocks
    - name: Compile
      run: make linux
    - name: Run unit tests
      run: go test -race -covermode atomic -coverprofile=coverage.out ./...
    - name: Convert coverage to lcov
      uses: jandelgado/gcov2lcov-action@2477d9ec11814a9326e7fdde8d315783d163edb7 # v1.0.8
    - name: Coveralls
      uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # v1.2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.lcov
