name: operator-e2e-tests

on: 
  pull_request:
  push:
    branches:
    - master

permissions:
  contents: read

jobs:
  tests:
    name: End-2-End tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
    - uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2.2.0
      with:
          go-version: "^1.17.4"
    - name: Make dependencies
      run: make deps mocks
    - name: Compile
      run: make linux
    - name: Run unit tests
      run: make test
    - name: Run end-2-end tests
      run: make e2e
